# _____                 _                   ____  _            _
#|  __ \               | |                 |  _ \| |          | |
#| |__) |__ _ _ __   __| | ___  _ __ ___   | |_) | | ___   ___| | __
#|  _  // _` | '_ \ / _` |/ _ \| '_ ` _ \  |  _ <| |/ _ \ / __| |/ /
#| | \ \ (_| | | | | (_| | (_) | | | | | | | |_) | | (_) | (__|   <
#|_|  \_\__,_|_| |_|\__,_|\___/|_| |_| |_| |____/|_|\___/ \___|_|\_\
#By Merciful

Enabled: false

Permission Name: "RB.RandomBlockGive"

Interval: 30

Same Item Per Player: false

Blacklisted Items:
- "AIR"
- "COMMAND_BLOCK"
- "CHAIN_COMMAND_BLOCK"
- "STRUCTURE_VOID"
- "VOID_AIR"