name: RandomBlock
version: '${project.version}'
main: dev.merciful.main.RandomBlock
api-version: 1.19
authors: [ Merciful ]
description: Get random item every xSeconds + can ban items
website: https://merciful.dev
